<?php
require_once 'config.php';
require_once 'includes/db.php';
require_once 'includes/auth.php';

// 啟動 Session
if (session_status() === PHP_SESSION_NONE) {
    session_start();
}

// 驗證登入狀態 (支援後台員工 或 Portal 客戶)
$is_staff = is_logged_in();
$is_client = isset($_SESSION['client_auth']);

if (!$is_staff && !$is_client) {
    die('拒絕訪問 Access Denied：請先登入系統。');
}

$invoice_id = (int)($_GET['id'] ?? 0);

if (!$invoice_id) {
    die('無效的發票編號 (Invalid invoice ID)');
}

// 獲取發票詳情
$invoice = db_fetch_one(
    "SELECT i.*, c.company_name, c.contact_person, c.email, c.phone, c.address, p.title as project_title
     FROM invoices i
     LEFT JOIN clients c ON i.client_id = c.id
     LEFT JOIN projects p ON i.project_id = p.id
     WHERE i.id = ?", 
    [$invoice_id]
);

if (!$invoice) {
    die('找不到該發票 (Invoice not found)');
}

// 核心安全限制：客戶只能看自己的單
if (!$is_staff && $is_client) {
    if ($invoice['client_id'] != $_SESSION['client_auth']['id']) {
        die('拒絕訪問 Access Denied：您無權查看其他公司的發票。');
    }
}

// ==========================================
// 語言設定邏輯 (已完美修復報錯問題)
// ==========================================
$lang_param = $_GET['lang'] ?? 'en';
$lang = in_array($lang_param, ['en', 'zh']) ? $lang_param : 'en';
$toggle_lang = $lang === 'en' ? 'zh' : 'en';

// 翻譯字典 (I18n)
$i18n = [
    'en' => [
        'tax_invoice' => 'INVOICE',
        'issue_date' => 'Issue Date:',
        'due_date' => 'Due Date:',
        'billed_to' => 'Billed To',
        'invoice_details' => 'Invoice Details',
        'project' => 'Project:',
        'status_label' => 'Status:',
        'generated_by' => 'Generated By:',
        'desc' => 'Description',
        'amount' => 'Amount',
        'default_title' => 'Professional Services & Consulting',
        'default_desc' => 'Development & Technical Support Services',
        'subtotal' => 'Subtotal:',
        'tax' => 'Tax',
        'total_due' => 'TOTAL DUE:',
        'pay_instructions' => 'Payment Instructions',
        'bank_name' => 'Bank Name:',
        'account_name' => 'Account Name:',
        'account_no' => 'Account No:',
        'fps_id' => 'FPS ID:',
        'payment_note' => 'Note: Please arrange payment via Bank Transfer or FPS before the due date. Kindly email the payment receipt or transaction reference to email@ysk.hk with the invoice number.',
        'thanks' => 'Thank you for your business!',
        'tagline' => 'Professional Digital Solutions',
        'system_gen' => 'This is a computer-generated document. No signature or stamp is required.',
        'hint' => 'Preview mode. Please use A4 size and check "Background graphics" when printing or saving as PDF.',
        'btn_print' => 'Print / Save PDF',
        'btn_toggle' => '🌐 切換為中文',
        'status' => [
            'paid' => 'PAID',
            'draft' => 'DRAFT',
            'sent' => 'PENDING',
            'overdue' => 'OVERDUE',
            'cancelled' => 'VOID'
        ]
    ],
    'zh' => [
        'tax_invoice' => '發票',
        'issue_date' => '開立日期:',
        'due_date' => '到期日期:',
        'billed_to' => '客戶資料',
        'invoice_details' => '發票詳情',
        'project' => '關聯項目:',
        'status_label' => '當前狀態:',
        'generated_by' => '開立系統:',
        'desc' => '項目說明',
        'amount' => '金額',
        'default_title' => '專業服務與顧問',
        'default_desc' => '系統開發與技術支援服務',
        'subtotal' => '小計:',
        'tax' => '稅項',
        'total_due' => '應付總額:',
        'pay_instructions' => '付款指示',
        'bank_name' => '銀行名稱:',
        'account_name' => '帳戶名稱:',
        'account_no' => '帳戶號碼:',
        'fps_id' => '轉數快 (FPS) ID:',
        'payment_note' => '註：請於到期日前透過銀行轉賬或轉數快 (FPS) 安排付款。付款後請將收據或交易編號連同發票號碼電郵至 email@ysk.hk。',
        'thanks' => '感謝您的惠顧！',
        'tagline' => '專業數碼解決方案',
        'system_gen' => '此乃電腦自動生成之文件，毋須簽名或蓋章。',
        'hint' => '預覽模式。列印或儲存為 PDF 時，請使用 A4 尺寸並勾選「背景圖形」。',
        'btn_print' => '列印 / 下載 PDF',
        'btn_toggle' => '🌐 English Version',
        'status' => [
            'paid' => '已結清',
            'draft' => '草稿',
            'sent' => '待付款',
            'overdue' => '已逾期',
            'cancelled' => '已作廢'
        ]
    ]
];

$t = $i18n[$lang];

// 設定狀態顯示
$status_color_map = [
    'paid' => '#16a34a', // 綠色
    'draft' => '#64748b', // 灰色
    'sent' => '#d97706', // 橙黃
    'overdue' => '#dc2626', // 紅色
    'cancelled' => '#475569' // 深灰
];
$status_bg_map = [
    'paid' => '#dcfce7',
    'draft' => '#f1f5f9',
    'sent' => '#fef3c7',
    'overdue' => '#fee2e2',
    'cancelled' => '#e2e8f0'
];

$inv_status = strtolower($invoice['status'] ?? 'draft');
$s_color = $status_color_map[$inv_status] ?? '#64748b';
$s_bg = $status_bg_map[$inv_status] ?? '#f1f5f9';
$status_text = $t['status'][$inv_status] ?? strtoupper($inv_status);

// Professional PDF-ready HTML
header('Content-Type: text/html; charset=utf-8');
?>
<!DOCTYPE html>
<html lang="<?= $lang === 'en' ? 'en' : 'zh-HK' ?>">
<head>
    <meta charset="UTF-8">
    <title>Invoice_<?= htmlspecialchars($invoice['invoice_number'] ?? '') ?>_YSK</title>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&family=Noto+Sans+TC:wght@400;500;700&display=swap" rel="stylesheet">
    <style>
        :root {
            --brand-color: #4f46e5;      /* YSK Indigo */
            --brand-dark: #3730a3;
            --text-main: #1e293b;        /* Slate 800 */
            --text-muted: #64748b;       /* Slate 500 */
            --text-light: #94a3b8;       /* Slate 400 */
            --border-color: #e2e8f0;     /* Slate 200 */
            --bg-light: #f8fafc;         /* Slate 50 */
            --page-width: 210mm;
            --page-height: 297mm;
        }

        body {
            font-family: 'Inter', 'Noto Sans TC', sans-serif;
            background-color: #cbd5e1;
            margin: 0;
            padding: 2rem 0;
            -webkit-font-smoothing: antialiased;
            color: var(--text-main);
        }

        /* 頂部操作列 */
        .action-bar {
            width: var(--page-width);
            margin: 0 auto 20px auto;
            background: #ffffff;
            padding: 16px 24px;
            border-radius: 12px;
            box-shadow: 0 4px 6px -1px rgba(0,0,0,0.05);
            display: flex;
            justify-content: space-between;
            align-items: center;
            box-sizing: border-box;
        }

        .action-info .title { font-size: 12pt; font-weight: 700; color: var(--text-main); margin-bottom: 2px; }
        .action-info .hint { font-size: 9pt; color: var(--text-muted); max-width: 400px; }

        .action-buttons {
            display: flex;
            gap: 12px;
            align-items: center;
        }

        .btn {
            padding: 10px 20px; border-radius: 8px; font-size: 10pt; font-weight: 600; 
            cursor: pointer; transition: 0.2s; text-decoration: none; display: inline-flex; align-items: center; justify-content: center;
        }
        .btn-print { background: var(--text-main); color: #fff; border: none; }
        .btn-print:hover { background: #0f172a; box-shadow: 0 4px 12px rgba(0,0,0,0.15); }
        
        .btn-lang { background: #f1f5f9; color: var(--brand-color); border: 1px solid #cbd5e1; }
        .btn-lang:hover { background: #e2e8f0; color: var(--brand-dark); }

        /* 真實 A4 紙張模擬 */
        .a4-sheet {
            width: var(--page-width);
            min-height: var(--page-height);
            margin: 0 auto;
            background: #ffffff;
            box-shadow: 0 25px 50px -12px rgba(0,0,0,0.15);
            box-sizing: border-box;
            position: relative;
            overflow: hidden;
            border-top: 12px solid var(--brand-color);
        }

        .content-layer {
            padding: 20mm 20mm;
            position: relative; 
            z-index: 1;
        }

        /* 浮水印 */
        .watermark {
            position: absolute;
            top: 45%; left: 50%;
            transform: translate(-50%, -50%) rotate(-30deg);
            font-size: 110px; font-weight: 800;
            border: 8px solid;
            border-radius: 20px; padding: 15px 40px;
            pointer-events: none; z-index: 0; letter-spacing: 8px;
            text-transform: uppercase;
        }

        /* Header 區域 */
        .header-table { width: 100%; margin-bottom: 40px; border-collapse: collapse; }
        .header-table td { vertical-align: top; }
        
        .company-info { font-size: 9.5pt; color: var(--text-muted); line-height: 1.6; margin-top: 15px; }
        .company-info strong { color: var(--text-main); font-size: 11pt; letter-spacing: 0.5px; }

        .invoice-title { font-size: 32pt; font-weight: 800; color: var(--text-main); letter-spacing: 2px; line-height: 1; margin-bottom: 10px; }
        .invoice-number { font-size: 14pt; font-weight: 600; color: var(--text-light); letter-spacing: 1px; }

        /* 資訊網格 (Bill To & Details) */
        .info-grid {
            display: grid;
            grid-template-columns: 1fr 1fr;
            gap: 40px;
            margin-bottom: 40px;
            background: var(--bg-light);
            border-radius: 12px;
            padding: 25px;
            border: 1px solid var(--border-color);
        }

        .info-section-title {
            font-size: 8.5pt; font-weight: 700; color: var(--text-muted);
            text-transform: uppercase; letter-spacing: 1px; margin-bottom: 12px;
        }

        .client-name { font-size: 13pt; font-weight: 700; color: var(--text-main); margin-bottom: 6px; }
        .client-details { font-size: 10pt; color: var(--text-main); line-height: 1.6; }

        .details-table { width: 100%; border-collapse: collapse; font-size: 10pt; }
        .details-table td { padding: 4px 0; }
        .details-table td.label { color: var(--text-muted); width: 40%; font-weight: 500; }
        .details-table td.value { color: var(--text-main); font-weight: 600; text-align: right; }

        .status-badge {
            display: inline-block; padding: 4px 12px; border-radius: 6px; font-size: 8.5pt;
            font-weight: 700; text-transform: uppercase; letter-spacing: 1px;
            background-color: <?= $s_bg ?>; color: <?= $s_color ?>;
        }

        /* 項目明細表 */
        .items-table { width: 100%; border-collapse: collapse; margin-bottom: 30px; }
        .items-table th {
            padding: 12px 16px;
            text-align: left; font-size: 8.5pt; font-weight: 700; color: var(--text-muted);
            text-transform: uppercase; letter-spacing: 1px;
            border-bottom: 2px solid var(--border-color);
        }
        .items-table th.text-right { text-align: right; }
        
        .items-table td {
            padding: 20px 16px;
            border-bottom: 1px solid var(--border-color);
            vertical-align: top;
        }
        .item-title { font-size: 11pt; font-weight: 600; color: var(--text-main); margin-bottom: 6px; }
        .item-desc { font-size: 9.5pt; color: var(--text-muted); white-space: pre-line; line-height: 1.5; }
        .item-amount { font-size: 11pt; font-weight: 600; color: var(--text-main); text-align: right; }

        /* 財務總計區 */
        .totals-wrapper { display: flex; justify-content: flex-end; margin-bottom: 40px; }
        .totals-table { width: 350px; border-collapse: collapse; }
        .totals-table td { padding: 10px 16px; text-align: right; }
        .totals-table td.label { color: var(--text-muted); font-size: 10pt; }
        .totals-table td.amount { font-weight: 600; font-size: 11pt; color: var(--text-main); }
        
        .total-due-row { background: var(--bg-light); border-radius: 8px; }
        .total-due-row td { padding: 16px; border-top: 2px solid var(--brand-color); }
        .total-due-row td.label { font-weight: 700; font-size: 11pt; color: var(--text-main); }
        .total-due-row td.amount { font-size: 18pt; font-weight: 800; color: var(--brand-color); }
        .currency { font-size: 11pt; color: var(--text-muted); margin-right: 6px; font-weight: 600; }

        /* 付款指示區 */
        .payment-instructions {
            border: 1px solid var(--border-color);
            border-radius: 12px;
            padding: 24px;
            margin-bottom: 40px;
        }
        .payment-title {
            font-size: 10pt; font-weight: 700; color: var(--text-main); margin-bottom: 16px;
            display: flex; align-items: center; text-transform: uppercase; letter-spacing: 0.5px;
        }
        .payment-title svg { width: 18px; height: 18px; margin-right: 8px; fill: var(--brand-color); }
        
        .bank-details {
            display: grid;
            grid-template-columns: 1fr 1fr;
            gap: 12px 24px;
            font-size: 10pt;
            color: var(--text-main);
        }
        .bank-details .row { display: flex; }
        .bank-details .lbl { color: var(--text-muted); width: 120px; font-weight: 500; }
        .bank-details .val { font-weight: 600; }
        
        .payment-note {
            margin-top: 20px; padding-top: 15px; border-top: 1px dashed var(--border-color);
            font-size: 9pt; color: var(--text-muted); font-style: italic; line-height: 1.5;
        }

        /* 頁尾 */
        .footer {
            text-align: center; font-size: 9pt; color: var(--text-muted);
            margin-top: 40px; padding-top: 20px;
        }
        .footer-thanks { font-size: 12pt; font-weight: 600; color: var(--text-main); margin-bottom: 8px; letter-spacing: 0.5px; }

        @media print {
            body { background: #fff; padding: 0; margin: 0; }
            .action-bar { display: none !important; }
            .a4-sheet { box-shadow: none; border-top: 12px solid var(--brand-color) !important; width: 100%; min-height: auto; }
            .content-layer { padding: 15mm; }
            .total-due-row td, .info-grid, .status-badge { -webkit-print-color-adjust: exact !important; print-color-adjust: exact !important; }
            @page { size: A4; margin: 0; }
        }
    </style>
</head>
<body>

    <div class="action-bar no-print">
        <div class="action-info">
            <div class="title"><?= htmlspecialchars($invoice['invoice_number'] ?? '') ?></div>
            <div class="hint"><?= $t['hint'] ?></div>
        </div>
        <div class="action-buttons">
            <a href="?id=<?= $invoice_id ?>&lang=<?= $toggle_lang ?>" class="btn btn-lang"><?= $t['btn_toggle'] ?></a>
            
            <button onclick="window.print()" class="btn btn-print">
                <svg style="width:16px;height:16px;vertical-align:middle;margin-right:6px;fill:currentColor;" viewBox="0 0 24 24"><path d="M19 8H5V3H19V8ZM16 11.5C16.83 11.5 17.5 10.83 17.5 10C17.5 9.17 16.83 8.5 16 8.5C15.17 8.5 14.5 9.17 14.5 10C14.5 10.83 15.17 11.5 16 11.5ZM22 11V19H18V22H6V19H2V11C2 9.34 3.34 8 5 8H19C20.66 8 22 9.34 22 11ZM16 19V15H8V19H16Z"/></svg>
                <?= $t['btn_print'] ?>
            </button>
        </div>
    </div>

    <div class="a4-sheet">
        
        <?php if ($inv_status === 'paid'): ?>
            <div class="watermark" style="color: rgba(22, 163, 74, 0.05); border-color: rgba(22, 163, 74, 0.05);"><?= $t['status']['paid'] ?></div>
        <?php elseif ($inv_status === 'cancelled'): ?>
            <div class="watermark" style="color: rgba(71, 85, 105, 0.05); border-color: rgba(71, 85, 105, 0.05);"><?= $t['status']['cancelled'] ?></div>
        <?php endif; ?>

        <div class="content-layer">
            
            <table class="header-table">
                <tr>
                    <td style="width: 50%;">
                        <img src="https://ysk.hk/logo.svg" alt="YSK Limited" style="height: 52px; width: auto; filter: brightness(0);">
                        <div class="company-info">
                            <strong>YSK LIMITED</strong><br>
                            Hong Kong<br>
                            Tel: +852 6160 4242 | Web: www.ysk.hk<br>
                            Email: email@ysk.hk
                        </div>
                    </td>
                    <td style="width: 50%; text-align: right;">
                        <div class="invoice-title"><?= $t['tax_invoice'] ?></div>
                        <div class="invoice-number">#<?= htmlspecialchars($invoice['invoice_number'] ?? '') ?></div>
                    </td>
                </tr>
            </table>

            <div class="info-grid">
                <div>
                    <div class="info-section-title"><?= $t['billed_to'] ?></div>
                    <div class="client-name"><?= htmlspecialchars($invoice['company_name'] ?? 'Unknown Client') ?></div>
                    <div class="client-details">
                        <?= htmlspecialchars($invoice['contact_person'] ?? '') ?><br>
                        <?= htmlspecialchars($invoice['email'] ?? '') ?><br>
                        <?= htmlspecialchars($invoice['phone'] ?? '') ?><br>
                        <?php if (!empty($invoice['address'])): ?>
                            <div style="margin-top: 8px; color: var(--text-muted);">
                                <?= nl2br(htmlspecialchars($invoice['address'])) ?>
                            </div>
                        <?php endif; ?>
                    </div>
                </div>
                
                <div>
                    <div class="info-section-title"><?= $t['invoice_details'] ?></div>
                    <table class="details-table">
                        <tr>
                            <td class="label"><?= $t['issue_date'] ?></td>
                            <td class="value"><?= htmlspecialchars($invoice['issue_date'] ?? '') ?></td>
                        </tr>
                        <tr>
                            <td class="label"><?= $t['due_date'] ?></td>
                            <td class="value"><?= htmlspecialchars($invoice['due_date'] ?? '') ?></td>
                        </tr>
                        <?php if (!empty($invoice['project_title'])): ?>
                        <tr>
                            <td class="label"><?= $t['project'] ?></td>
                            <td class="value"><?= htmlspecialchars($invoice['project_title']) ?></td>
                        </tr>
                        <?php endif; ?>
                        <tr>
                            <td class="label"><?= $t['status_label'] ?></td>
                            <td class="value">
                                <div class="status-badge">
                                    <?= $status_text ?>
                                </div>
                            </td>
                        </tr>
                    </table>
                </div>
            </div>

            <table class="items-table">
                <thead>
                    <tr>
                        <th style="width: 75%;"><?= $t['desc'] ?></th>
                        <th class="text-right" style="width: 25%;"><?= $t['amount'] ?> (HKD)</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>
                            <div class="item-title">
                                <?= !empty($invoice['project_title']) ? htmlspecialchars($invoice['project_title']) : $t['default_title'] ?>
                            </div>
                            <div class="item-desc">
                                <?= !empty($invoice['notes']) ? nl2br(htmlspecialchars($invoice['notes'])) : $t['default_desc'] ?>
                            </div>
                        </td>
                        <td class="item-amount">
                            <?= number_format($invoice['subtotal'] ?? 0, 2) ?>
                        </td>
                    </tr>
                </tbody>
            </table>

            <div class="totals-wrapper">
                <table class="totals-table">
                    <tr>
                        <td class="label"><?= $t['subtotal'] ?></td>
                        <td class="amount"><?= number_format($invoice['subtotal'] ?? 0, 2) ?></td>
                    </tr>
                    <?php if (($invoice['tax_percent'] ?? 0) > 0): ?>
                    <tr>
                        <td class="label"><?= $t['tax'] ?> (<?= htmlspecialchars($invoice['tax_percent']) ?>%):</td>
                        <td class="amount"><?= number_format(($invoice['total_amount'] ?? 0) - ($invoice['subtotal'] ?? 0), 2) ?></td>
                    </tr>
                    <?php endif; ?>
                    <tr class="total-due-row">
                        <td class="label"><?= $t['total_due'] ?></td>
                        <td class="amount">
                            <span class="currency">HK$</span><?= number_format($invoice['total_amount'] ?? 0, 2) ?>
                        </td>
                    </tr>
                </table>
            </div>

            <div class="payment-instructions">
                <div class="payment-title">
                    <svg viewBox="0 0 24 24"><path d="M12 3L2 8h20L12 3zM2 10v9h2v-9H2zm6 0v9h2v-9H8zm6 0v9h2v-9h-2zm6 0v9h2v-9h-2zM2 21v2h20v-2H2z"/></svg>
                    <?= $t['pay_instructions'] ?>
                </div>
                <div class="bank-details">
                    <div class="row"><div class="lbl"><?= $t['bank_name'] ?></div><div class="val">HSBC (Hong Kong)</div></div>
                    <div class="row"><div class="lbl"><?= $t['account_name'] ?></div><div class="val">YSK LIMITED</div></div>
                    <div class="row"><div class="lbl"><?= $t['account_no'] ?></div><div class="val">691-239008-838</div></div>
                    <div class="row"><div class="lbl"><?= $t['fps_id'] ?></div><div class="val">+852 6160 4242</div></div>
                </div>
                <div class="payment-note">
                    <?= $t['payment_note'] ?>
                </div>
            </div>

            <div class="footer">
                <div class="footer-thanks"><?= $t['thanks'] ?></div>
                <div>YSK Limited • <?= $t['tagline'] ?></div>
                <div style="margin-top: 6px; font-size: 8pt; color: #94a3b8;"><?= $t['system_gen'] ?></div>
            </div>

        </div>
    </div>

</body>
</html>